### ISSUE TITLE
[suggestion] TTDM balance improvment

### ISSUE THREAD

**Issue by rogo921** [CTalvio/MentalEdge.BetterTeamBalance#2]
Hello,BTB really did a good job on  team balance, however i noticed that your balance algorithm is based on ‘score’ and ‘kd’，which may not suitable to ttdm. For the most important thing is that ttdm is literally a damage—racing. The kills are less important than damage. For example, if a ronin player stolen several kills from others while he only did little (less than 10k) damage. In current alg he would be treated as a powerful player. Meantime a master ronin player ususally did tons of damage(90k~100k),but he may have a normal kd performance. So  I adjusted the alg in the .nut file. Player`s strength now roughly speaking is “damage*0.5+exchange ratio*0.3+kills*0.2”
damage：player`s damage/10k
exchange ratio：player`s damage / his deaths+1 (his average damage per life)
kills：player`s kills * 10k(average titan life points number)/10k
the rest alg remain unchanged and the balance effect in follow games were significance.
Besides,if you can set a “kickoff noob” function which would be great for ttdm is seriously teamwork mode，and my server is open for experienced players in order to get a hardcore combat gameplay. Mixed topplayer and newone in one room only make them both lost the fun of game.
Thanks for your mod！

**Comment by CTalvio** [comment]
No, the Ronin would get very little reward out of killstealing. It used to be like that, but I see great minds think alike :D. In version 2.0.1, I added TTDM specific code. I've been adding mode-specific objectiverate calculations to BTB ever since I moved to "rate" based player evaluation instead of final "kd*score" based evaluation in version 2.

The old system had issues in normal games to. A good player who was there for only half a match could have a lower evaluation than an average player that was there for the whole match, and that would throw off the balance in the next match.

You can see the TTDM specific formula, here: https://github.com/CTalvio/MentalEdge.BetterTeamBalance/blob/49f2b670ae139ae51f1c308160cc49bdb88191a5/mod/scripts/vscripts/teambalance.nut#L320

Any adjustments to improve it would be welcome.
